
all:
	
	touch ${PRODUCT}.uwsgi.ini
	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini
	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini

	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini
	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini
	
	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini
	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini
	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini

	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini

	echo "[uwsgi]" >>${PRODUCT}.uwsgi.ini
